### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Marco224** [jcltravels/Switch-for-Safari#1]
The Dark Mode on is not applied on some "HTML5>>iframe" elements, also if activated as soon as you enter a site there will be a delay in the application of the dark mode that causes an unwanted flash effect

![image](https://github.com/jcltravels/Switch-for-Safari/assets/38478493/af09b205-9d0f-4611-806d-ca73bbaddb78)

https://webbrowsertools.com/darkmode/

**Comment by jcltravels** [comment]
Will be fixed in v2.3
![Image from iOS (1)](https://github.com/jcltravels/Switch-for-Safari/assets/60549809/ee2d2796-962a-4693-80e8-585b66c0262c)

**Comment by jcltravels** [comment]
version 2.3 released.
